### ISSUE TITLE
Propose new way

### ISSUE THREAD

**Issue by cecekpawon** [afterdesign/termX#42]
Instead of manually set mode in settings, maybe we can do [this](https://github.com/cecekpawon/MacTerminal)?

![macterminal](https://cloud.githubusercontent.com/assets/8464050/11030635/d8aee190-8701-11e5-9f82-c167efce68fd.png)

**Comment by afterdesign** [comment]
That's a great idea ! I think I can do this next week. Still the mode will be usefull for the shortcut. Maybe I'll add option to change mode with command palette. Thanks for idea !

**Comment by cecekpawon** [comment]
Yes sir, and maybe you can add more tweak like able to exec from context menu in document instead of sidebar (if hidden)..
