### ISSUE TITLE
"Message not understood" when using iTerm

### ISSUE THREAD

**Issue by shankiesan** [afterdesign/termX#44]
When using the following configuration, with iTerm:

```
{
      "directory_mode" : "project",
      "terminal"   :  "iterm"
  }
```

iTerm simply opens my default directory, rather than the project directory. I get the following error in the Sublime console:

```
'---MacTerminal DEBUG START---'
{'cmd': '/usr/bin/osascript /Users/shankie/Library/Application Support/Sublime Text 3/Packages/MacTerminal/macterminal_iterm.js /Users/shankie/Sites/proper-build',
 'directory_mode': 'project',
 'ext_language': 'js',
 'paths': ['/Users/shankie/Sites/proper-build'],
 'process_err': b'/Users/shankie/Library/Application Support/Sublime Text 3/Packages/MacTerminal/macterminal_iterm.js:418:495: execution error: Error on line 23: Error: Message not understood. (-1708)\n',
 'process_out': b''}
'---MacTerminal DEBUG END---'
```

Any ideas? Cheers!

**Comment by dale-ackerman** [comment]
I am having this issue also...

`'---MacTerminal DEBUG START---'
{'cmd': '/usr/bin/osascript /Users/dackerm/Library/Application Support/Sublime Text 3/Packages/MacTerminal/macterminal_iterm.js /Users/dackerm/Projects/bi-sso-demo',
 'directory_mode': 'project',
 'ext_language': 'js',
 'paths': ['/Users/dackerm/Projects/bi-sso-demo'],
 'process_err': b'/Users/dackerm/Library/Application Support/Sublime Text 3/Packages/MacTerminal/macterminal_iterm.js:418:495: execution error: Error on line 23: Error: Message not understood. (-1708)\n',
 'process_out': b''}
'---MacTerminal DEBUG END---'`
