### ISSUE TITLE
Can't get termX to activate

### ISSUE THREAD

**Issue by alextegelid** [afterdesign/termX#54]
I've been using MacTerminal for some time but lately it's been acting up by not cd:ing into the folder that I'm currently in.
So today I decided to try some alternatives and removed MacTerminal, but in lack of anything better I tried installing it again via Package Control. Of course that didn't work since it's been renamed to termX (and is currently not available from Package Control?), so I manually cloned the master branch (652aed4) into my Packages folder.

Now I can't get the `open_termx_terminal` command to do anything at all. Running the command manually in the console does nothing either. Also I don't see anything related to termX in the command palette.

I'm using Sublime Text, Stable Channel, build 3114

![image](https://cloud.githubusercontent.com/assets/7058721/17480450/3c345bc6-5d78-11e6-9ec0-69d554145709.png)

**Comment by alextegelid** [comment]
Might this be related to [this function](https://github.com/afterdesign/termX/blob/master/open_termx_terminal.py#L85) being named efter the old plugin name?  I'm not familiar with the conventions around writing ST plugins, but I'm throwing in a wildcard here :)

**Comment by afterdesign** [comment]
Thanx @alextegelid for all info ! I was distracted I guess while doing this changes.

**Comment by alextegelid** [comment]
Anytime! Glad I could help :)
