### ISSUE TITLE
Old setting file is being loaded

### ISSUE THREAD

**Issue by alextegelid** [afterdesign/termX#55]
I noticed that termX seems to load the settings file named after the old plugin name `MacTerminal.sublime-settings` ([Source](https://github.com/afterdesign/termX/blob/master/open_termx_terminal.py#L93)).
But when accessing the settings file from the main menu it points to the new name `termX.sublime-settings` ([Source](https://github.com/afterdesign/termX/blob/master/Main.sublime-menu#L28))

**Comment by afterdesign** [comment]
This one also should work fine from now.
