### ISSUE TITLE
No longer in Package Control 

### ISSUE THREAD

**Issue by garyking** [afterdesign/termX#56]
So what's the best way to install this package?

**Comment by afterdesign** [comment]
I've opened PR for package control. Still waiting. You can clone this package to your sublime packages directory.

**Comment by VictorKilo** [comment]
It will be easier to maintain your user settings through Package Control if you just add this Git Repository with `Package Control: Add Repository`.  Once added, you can install termX through the standard Package Control interface.

**Comment by afterdesign** [comment]
And it's in package control again !
