### ISSUE TITLE
Readme.md needs updating

### ISSUE THREAD

**Issue by divinites** [afterdesign/termX#57]
Problem:

1. `termx.sublime-settings` does not work, actually, when I looked at the source code, the settings file is still hardcoded as `MacTerminal.sublime-settings`

2. the command is not `open_terminal`, again, in the source code, the correct command is `open_mac_terminal`.

**Comment by afterdesign** [comment]
First of all this is open source and you can create PR with fixes.
Second of all I've just pushed 5.0.1 tag. Don't know why I haven't pushed it earlier.
